services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: evolution-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: evolution_db
      POSTGRES_USER: evolution_user
      POSTGRES_PASSWORD: evolution_pass_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Evolution API
  evolution-api:
    image: evolution-api:latest
    container_name: evolution-api-navigator
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      # Configurações básicas
      SERVER_URL: http://localhost:8080
      AUTHENTICATION_API_KEY: navigator-evolution-key-2025-secure
      LOG_LEVEL: ERROR
      CORS_ORIGIN: "*"
      
      # Banco de dados PostgreSQL
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://evolution_user:evolution_pass_2025@postgres:5432/evolution_db?schema=evolution_api"
      
      # Webhook para N8N
      WEBHOOK_GLOBAL_URL: https://hndll.app.n8n.cloud/webhook/evolution-webhook
      WEBHOOK_GLOBAL_ENABLED: true
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: false
      
    volumes:
      - evolution_data:/evolution
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manager/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  evolution_data:
    driver: local
