services:
  evolution-api:
    # Usar imagem oficial pré-compilada (evita erros de build)
    image: evolutionapi/evolution-api:1.0.0
    container_name: evolution-api-navigator
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Configurações básicas
      SERVER_URL: http://localhost:8080
      AUTHENTICATION_API_KEY: navigator-evolution-key-2025-secure
      
      # Banco de dados (usar SQLite para simplicidade)
      DATABASE_ENABLED: true
      DATABASE_CONNECTION_URI: sqlite:./evolution.db
      
      # Logs
      LOG_LEVEL: ERROR
      
      # Configurações de segurança
      CORS_ORIGIN: "*"
      
      # Configurações específicas do Navigator
      WEBHOOK_GLOBAL_URL: https://hndll.app.n8n.cloud/webhook/evolution-webhook
      WEBHOOK_GLOBAL_ENABLED: true
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: false
      WEBHOOK_GLOBAL_EVENTS: "MESSAGES_UPSERT,MESSAGES_UPDATE,MESSAGES_DELETE,SEND_MESSAGE,CONTACTS_SET,CONTACTS_UPSERT,CONTACTS_UPDATE,PRESENCE_UPDATE,CHATS_SET,CHATS_UPSERT,CHATS_UPDATE,CHATS_DELETE,GROUPS_UPSERT,GROUP_UPDATE,GROUP_PARTICIPANTS_UPDATE,CONNECTION_UPDATE,CALL,NEW_JWT_TOKEN"
      
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
      - evolution_logs:/evolution/logs
      - evolution_database:/evolution/database
    networks:
      - evolution-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manager/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  evolution_instances:
    driver: local
  evolution_store:
    driver: local
  evolution_logs:
    driver: local
  evolution_database:
    driver: local

networks:
  evolution-network:
    driver: bridge



