services:
  evolution-api:
    # Usar imagem oficial pré-compilada (evita erros de build)
    image: evolution-api:latest
    container_name: evolution-api-navigator
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Configurações básicas mínimas
      SERVER_URL: http://localhost:8080
      AUTHENTICATION_API_KEY: navigator-evolution-key-2025-secure
      LOG_LEVEL: ERROR
      CORS_ORIGIN: "*"
      
      # Banco de dados simples
      DATABASE_PROVIDER: "sqlite"
      DATABASE_CONNECTION_URI: "file:./evolution.db"
      
      # Webhook básico
      WEBHOOK_GLOBAL_URL: https://hndll.app.n8n.cloud/webhook/evolution-webhook
      WEBHOOK_GLOBAL_ENABLED: true
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: false
      
    volumes:
      - evolution_data:/evolution
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manager/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  evolution_data:
    driver: local
