services:
  - type: web
    name: policy-agent-poc
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx ts-node src/server.ts
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        value: changeme


